# Generated by Django 5.0 on 2024-01-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_rooms_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='host',
        ),
    ]
