# Generated by Django 5.0 on 2024-01-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rename_user_message_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='points',
        ),
    ]
