# Generated by Django 5.0 on 2024-01-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_message_options_roomrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
